title: Rhys's Demo Site
author: rziemer
email: rziemer@sogetthis.com
description: > # this means to ignore newlines until "baseurl:"
  Rhys's Demo Site on GitHub

# social links
github_username:  rziemer

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
